import {Dimensions, StyleSheet} from 'react-native';

const {width: WIDTH} = Dimensions.get('window');
const BOX_HEIGHT = (WIDTH * 500) / 400;

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  box: {
    width: WIDTH,
    height: BOX_HEIGHT,
    overflow: 'hidden',
  },
  bottom: {
    position: 'absolute',
    bottom: -130,
    alignSelf: 'center',
    backgroundColor: '#fb6971',
    width: WIDTH - 80,
    height: WIDTH - 80,
    borderTopLeftRadius: 140,
    borderTopRightRadius: 140,
    overflow: 'hidden',
  },
  shirt: {
    position: 'absolute',
    bottom: 130,
    width: 180,
    height: 90,
    alignSelf: 'center',
    backgroundColor: '#6192a1',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  leftShirtStrap: {
    position: 'absolute',
    top: 0,
    left: 70,
    width: 30,
    height: 100,
    backgroundColor: '#6192a1',
    transform: [{rotate: '345deg'}],
  },
  rightShirtStrap: {
    position: 'absolute',
    top: 0,
    right: 70,
    width: 30,
    height: 100,
    backgroundColor: '#6192a1',
    transform: [{rotate: '15deg'}],
  },
  shirtButton: {
    position: 'absolute',
    top: 80,
    left: 85,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#fff',
    shadowOffset: {
      width: 105,
      height: 0,
    },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 5,
  },

  head: {
    flex: 1,
  },
  neck: {
    position: 'absolute',
    bottom: 120,
    alignSelf: 'center',
    width: 70,
    height: 100,
    backgroundColor: '#ffcfcc',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },
  neckShadow: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0,0,0,0.1)',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
  },

  face: {
    position: 'absolute',
    top: 100,
    alignSelf: 'center',
    width: 160,
    height: 180,
    backgroundColor: '#ffcfcc',
    zIndex: 12,
    borderTopLeftRadius: 70,
    borderTopRightRadius: 70,
    borderBottomLeftRadius: 80,
    borderBottomRightRadius: 80,
  },
  eyes: {
    position: 'absolute',
    top: 50,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '65%',
  },
  eye: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  pupil: {
    width: 18,
    height: 18,
    borderRadius: 10,
    backgroundColor: '#3d5d89',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{translateX: -10}, {translateY: 2}],
  },
  blackPupil: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#111',
  },
  eyebrow: {
    position: 'absolute',
    top: -8,
    left: 0,
    width: 40,
    height: '50%',
    backgroundColor: '#ffcfcc',
    shadowColor: '#111',
    borderRadius: 60,
    shadowOffset: {
      width: 0,
      height: -3,
    },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 0,
    zIndex: -1,
  },
  mouth: {
    position: 'absolute',
    bottom: 30,
    alignSelf: 'center',
    width: 60,
    height: 30,
    overflow: 'hidden',
  },
  mouthInside: {
    position: 'absolute',
    bottom: 0,
    alignSelf: 'center',
    width: 60,
    height: 60,
    backgroundColor: '#ff4e57',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },

  hair: {
    position: 'absolute',
    bottom: -20,
    alignSelf: 'center',
    width: 230,
    height: 450,
    backgroundColor: '#111',
    borderTopLeftRadius: 200,
    borderTopRightRadius: 200,
  },
});
